### ISSUE TITLE
Secure an ISO to submit ticket to NSOC to unblock google apps

### ISSUE THREAD

**Issue by gabrielzucker** [department-of-veterans-affairs/homeless-data-sharing#18]

**Comment by ShawnArnwine** [comment]
I'll inquire, but you'll also want Nicole to try and run this down

**Comment by gabrielzucker** [comment]
ok

**Comment by gabrielzucker** [comment]
don't mean to punt back to you, but Nicole wasn't 100% clear on this - suspects the right person is Alan. is this correct? Sorry, I'm in over my head on this specific subject...

**Comment by ShawnArnwine** [comment]
No problem. If Alan is running the show then yes he can inquire.

**Comment by ShawnArnwine** [comment]
Just sent an email (CC'd you) to the two ISOs best positioned to support this effort. We'll see if either can or at least can point us to those that could.
